version: '3.8'

services:
  db:
    image: postgres:13
    container_name: Postgres_Joplin
    restart: unless-stopped
    networks:
      - joplin
    volumes:
      - /mnt/user/appdata/Postgres_Joplin:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DATABASE}

  app:
    image: joplin/server:latest
    container_name: Joplin_Postgres
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - joplin
    ports:
      - 22300:22300
    environment:
      - APP_PORT=22300
      - APP_BASE_URL=${APP_BASE_URL}
      - DB_CLIENT=pg
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=db

networks:
  joplin:
    driver: bridge