version: '3.8'

services:
  planka:
    image: meltyshev/planka:latest
    container_name: Planka_Postgres
    command: >
      bash -c
        "for i in `seq 1 30`; do
          ./start.sh &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 seconds...\";
          sleep 5;
        done; (exit $$s)"
    restart: unless-stopped
    networks:
      - planka
    volumes:
      - /mnt/user/appdata/Planka_Postgres/user-avatars:/app/public/user-avatars
      - /mnt/user/appdata/Planka_Postgres/project-background-images:/app/public/project-background-images
      - /mnt/user/appdata/Planka_Postgres/attachments:/app/private/attachments
    ports:
      - 3000:1337
    environment:
      - BASE_URL=http://localhost:3000
      - TRUST_PROXY=0
      - DATABASE_URL=postgresql://postgres@postgres/planka
      - SECRET_KEY=notsecretkey
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    networks:
      - planka
    volumes:
      - /mnt/user/appdata/Postgres_Planka/db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=planka
      - POSTGRES_HOST_AUTH_METHOD=trust

networks:
  planka:
    driver: bridge