version: '3'

services:
  onlyoffice-documentserver:
    container_name: Onlyoffice-Document-Server
    image: onlyoffice/documentserver:latest
    networks:
      - onlyofficed
    depends_on:
      - onlyoffice-postgresql
      - onlyoffice-rabbitmq
    environment:
      - DB_TYPE=postgres
      - DB_HOST=onlyoffice-postgresql
      - DB_PORT=5432
      - DB_NAME=onlyoffice
      - DB_USER=onlyoffice
      - AMQP_URI=amqp://guest:guest@onlyoffice-rabbitmq
      # Uncomment strings below to enable the JSON Web Token validation.
      #- JWT_ENABLED=true
      #- JWT_SECRET=secret
      #- JWT_HEADER=Authorization
      #- JWT_IN_BODY=true
    ports:
      - 4218:80
      - 4219:443
    stdin_open: true
    restart: always
    stop_grace_period: 60s
    volumes:
       - /mnt/user/appdata/Onlyoffice-Document-Server/ssl:/var/www/onlyoffice/Data
       - /mnt/user/appdata/Onlyoffice-Document-Server/log:/var/log/onlyoffice
       - /mnt/user/appdata/Onlyoffice-Document-Server/cache:/var/lib/onlyoffice/documentserver/App_Data/cache/files
       - /mnt/user/appdata/Onlyoffice-Document-Server/example:/var/www/onlyoffice/documentserver-example/public/files
       - /mnt/user/appdata/Onlyoffice-Document-Server/fonts:/usr/share/fonts

  onlyoffice-rabbitmq:
    container_name: Onlyoffice-Document-Server-Rabbitmq
    image: rabbitmq
    networks:
      - onlyofficed
    restart: always
    expose:
      - 5672

  onlyoffice-postgresql:
    container_name: Onlyoffice-Document-Server-Postgresql
    image: postgres:9.5
    networks:
      - onlyofficed
    environment:
      - POSTGRES_DB=onlyoffice
      - POSTGRES_USER=onlyoffice
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    expose:
      - 5432
    volumes:
      - /mnt/user/appdata/Onlyoffice-Document-Server-Postgresql:/var/lib/postgresql

networks:
  onlyofficed:
    driver: bridge