version: '3'

services:
  onlyoffice-mysql-server:
    container_name: Onlyoffice-Mysql-Server
    image: mysql:8.0.29
    environment:
     - MYSQL_ROOT_PASSWORD=my-secret-pw
    networks:
     - onlyoffice
    stdin_open: true
    tty: true
    restart: always
    tmpfs: /var/log/mysql/
    volumes:
     - /mnt/user/appdata/Onlyoffice-Mysql-Server/config/mysql/conf.d:/etc/mysql/conf.d
     - /mnt/user/appdata/Onlyoffice-Mysql-Server/config/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
     - /mnt/user/appdata/Onlyoffice-Mysql-Server/mysql_data:/var/lib/mysql

  onlyoffice-community-server:
    container_name: Onlyoffice-Community-Server
    image: onlyoffice/communityserver:12.0.1.1748
    depends_on:
     - onlyoffice-mysql-server
     - onlyoffice-elasticsearch
    environment:
     - ONLYOFFICE_CORE_MACHINEKEY=core_secret
     - CONTROL_PANEL_PORT_80_TCP=80
     - CONTROL_PANEL_PORT_80_TCP_ADDR=onlyoffice-control-panel
     - MYSQL_SERVER_ROOT_PASSWORD=my-secret-pw
     - MYSQL_SERVER_DB_NAME=onlyoffice
     - MYSQL_SERVER_HOST=onlyoffice-mysql-server
     - MYSQL_SERVER_USER=onlyoffice_user
     - MYSQL_SERVER_PASS=onlyoffice_pass
     - ELASTICSEARCH_SERVER_HOST=onlyoffice-elasticsearch
     - ELASTICSEARCH_SERVER_HTTPPORT=9200
    networks:
     - onlyoffice
    ports:
     - 4216:80
     - 4217:443
     - 5222:5222
    stdin_open: true
    tty: true
    restart: always
    privileged: true
    volumes:
     - /mnt/user/appdata/Onlyoffice-Community-Server/community_data:/var/www/onlyoffice/Data
     - /mnt/user/appdata/Onlyoffice-Community-Server/community_log:/var/log/onlyoffice
     - /mnt/user/appdata/Onlyoffice-Community-Server/community_letsencrypt:/etc/letsencrypt
     - /sys/fs/cgroup:/sys/fs/cgroup:ro
     - /mnt/user/appdata/Onlyoffice-Community-Server/certs:/var/www/onlyoffice/Data/certs

  onlyoffice-elasticsearch:
    image: onlyoffice/elasticsearch:7.16.3
    container_name: Onlyoffice-Elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g -Dlog4j2.formatMsgNoLookups=true
      - indices.fielddata.cache.size=30%
      - indices.memory.index_buffer_size=30%
    networks:
    - onlyoffice    
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - /mnt/user/appdata/Onlyoffice-Elasticsearch/es_data:/usr/share/elasticsearch/data
    expose:
      - 9200
      - 9300

  onlyoffice-control-panel:
    container_name: Onlyoffice-Control-Panel
    depends_on:
     - onlyoffice-community-server
    image: onlyoffice/controlpanel:3.1.1.467
    environment:
     - ONLYOFFICE_CORE_MACHINEKEY=core_secret
    expose:
      - 80
      - 443
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/user/appdata/Onlyoffice-Control-Panel/controlpanel_data:/var/www/onlyoffice/Data
      - /mnt/user/appdata/Onlyoffice-Control-Panel/controlpanel_log:/var/log/onlyoffice
    networks:
      - onlyoffice
    stdin_open: true
    tty: true

networks:
  onlyoffice:
    driver: bridge